#!/bin/sh

emerge gentoo-sources

DIR_COUNT=$(find /usr/src/ -maxdepth 1 -type d -name 'linux-*' | wc -l)
[ "$DIR_COUNT" -gt "1" ] || { echo "There is only one linux directory. The script stops..."; exit 1; }

cd "$(find /usr/src/ -maxdepth 1 -type d -name 'linux-*' | sort -rV | head -n 1)" &&

cp "$(find /usr/src/ -maxdepth 1 -type d -name 'linux-*' | sort -rV | head -n 2 | tail -n 1)/.config" . &&

make olddefconfig &&

make -j$(nproc) &&

emerge nvidia-drivers &&

make modules_install &&

cp arch/x86/boot/bzImage /boot/EFI/BOOT/BOOTX64.EFI &&

rm -rf "$(find /usr/src/ -maxdepth 1 -type d -name 'linux-*' | sort -rV | head -n 2 | tail -n 1)"
